code/master/app/home/models.py
#create db models/tables
from sqlalchemy import Binary, Column, Integer, String

from app import db
from app.base.models import User

class Sales(db.Model):

    __tablename__ = 'Sales'

    id = Column(Integer, primary_key=True)
    cust_fname = db.Column(db.String(255))
    cust_lname = db.Column(db.String(255))
    email = db.Column(db.String(255))
    cust_phone_no = db.Column(db.String(50))
    product_code = db.Column(db.String(10))
    qnt = db.Column(db.String(10))
    warranty_status = db.Column(db.String(10))
    delivery = db.Column(db.String(10))
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)

    def __repr__(self):
        return str(self.cust_fname,self.email)

code/master/app/home/forms.py
#create wtf forms
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, PasswordField, BooleanField,SubmitField, TextAreaField, validators
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from wtforms.fields.html5 import EmailField

class AddsalesForm(FlaskForm):
    cust_fname = StringField('First Name', validators=[DataRequired()])
    cust_lname = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    cust_phone_no = IntegerField('Customer Phone Number', [DataRequired()])
    product_code = StringField('Product Code', [DataRequired()])
    qnt = IntegerField('Quantity', [DataRequired()])
    warranty_status = StringField('Warranty Status')
    delivery = BooleanField("Delivery")
    submit = SubmitField('Submit')

class UpdatesalesForm(FlaskForm):
    cust_fname = StringField('First Name', validators=[DataRequired()])
    cust_lname = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    cust_phone_no = IntegerField('Customer Phone Number', [DataRequired()])
    product_code = StringField('Product Code', [DataRequired()])
    qnt = IntegerField('Quantity', [DataRequired()])
    warranty_status = StringField('Warranty Status')
    delivery = BooleanField("Delivery")
    submit = SubmitField('Submit')


class RecommendForm(FlaskForm):
    recommend = BooleanField(label=("Recommend for approval"))
    submit = SubmitField('Submit')

class ApproveForm(FlaskForm):
    approve = BooleanField(label=("Approve the application"))
    submit = SubmitField('Submit')

class MessageForm(FlaskForm):
    message = TextAreaField(label =('Message'), validators=[
        DataRequired(), Length(min=0, max=140)])
    submit = SubmitField('Submit')

code/master/app/home/__init__.py
#register blueprint
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

code/master/app/home/routes.py
#set up endpoints and system logic
from app.home import blueprint
from flask import render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app import login_manager
from app import db
from app.base.models import User
from app.home.models import Sales
from app.home.forms import AddsalesForm, UpdatesalesForm
from jinja2 import TemplateNotFound

@blueprint.route('/index')
@login_required
def index():

    return render_template('index.html', segment='index')


@blueprint.route("sales/add", methods=['GET', 'POST'])
@login_required
def add_sales():
    form = AddsalesForm()
    if form.validate_on_submit():
        sales = Sales(
                    cust_fname = form.cust_fname.data,
                    cust_lname = form.cust_lname.data,
                    email = form.email.data,
                    cust_phone_no = form.cust_phone_no.data,
                    product_code = form.product_code.data,
                    qnt = form.qnt.data,
                    warranty_status = form.warranty_status.data,
                    delivery = form.delivery.data,
                    author=current_user)
        db.session.add(sales)
        db.session.commit()
        flash('Entry completed successfully!','success')
        return redirect(url_for('home_blueprint.add_sales'))    
    return render_template("add-sales.html", form=form)



@blueprint.route("sales/<int:sales_id>/update", methods=['GET', 'POST'])
@login_required
def update_sales(sales_id):
    sales = Sales.query.get_or_404(sales_id)
    if sales.author != current_user:
        abort(403)
    form = UpdatesalesForm()
    if form.validate_on_submit():
        sales.cust_fname = form.cust_fname.data
        sales.cust_lname = form.cust_lname.data
        sales.email = form.email.data
        sales.cust_phone_no = form.cust_phone_no.data
        sales.product_code = form.product_code.data
        sales.qnt = form.qnt.data
        sales.warranty_status = form.warranty_status.data
        sales.delivery = form.delivery.data
        db.session.commit()
        flash('Entry Updated successfully!','success')
        return redirect(url_for('home_blueprint.sales_dashboard'))
    elif request.method == 'GET':
        form.cust_fname.data = sales.cust_fname
        form.cust_lname.data = sales.cust_lname
        form.email.data = sales.email
        form.cust_phone_no.data = sales.cust_phone_no
        form.product_code.data = sales.product_code
        form.qnt.data = sales.qnt
        form.warranty_status.data = sales.warranty_status
        form.delivery.data = sales.delivery
    return render_template("update-sales.html", form=form)

@blueprint.route("sales/<int:sales_id>/delete", methods=['POST'])
@login_required
def delete_sales(sales_id):
    sales = Sales.query.get_or_404(sales_id)
    if sales.author != current_user:
        abort(403)
    db.session.delete(sales)
    db.session.commit()
    flash('Entry has been deleted!', 'success')
    return redirect(url_for('home_blueprint.sales_dashbord'))


@blueprint.route("/sales-dashboard")
def sales_dashboard():
    data = Sales.query.all()
    return render_template('sales.html',data=data)


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith( '.html' ):
            template += '.html'

        # Detect the current page
        segment = get_segment( request )

        # Serve the file (if exists) from app/templates/FILE.html
        return render_template( template, segment=segment )

    except TemplateNotFound:
        return render_template('page-404.html'), 404
    
#    except:
#        return render_template('page-500.html'), 500

# Helper - Extract current page name from request 
def get_segment( request ): 

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment    

    except:
        return None  

code/master/app/home/templates/Sales.html
{% extends "layouts/base.html" %}

{% block title %} Datatables {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary card-header-icon">
          <div class="card-icon">
            <i class="material-icons">assignment</i>
          </div>
          <h4 class="card-title">Sales</h4>
        </div>
        <div class="card-body">
          <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
          </div>
          <div class="material-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                  
                  <th>Customer</th>
                  <th>Product</th>
                  <th>Qnt</th>
                  <th>Cashier</th>
                  <th>Date</th>
                  <th class="disabled-sorting text-right">Actions</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  
                  <th>Customer</th>
                  <th>Product</th>
                  <th>Qnt</th>
                  <th>Cashier</th>
                  <th>Date</th>
                  <th class="text-right">Actions</th>
                </tr>
              </tfoot>
              <tbody>
                {% for entry in data %}
                <tr>
                  <td>{{entry.cust_fname}} {{entry.cust_lname}}</td>
                  <td>{{entry.product_code}}</td>
                  <th>{{entry.qnt}}</th>
                  <td>{{entry.author.username}}</td>
                  <td>2011/04/25</td>
                  {% if entry.author == current_user %}
                  <td class="text-right">
                    <a href="#" class="btn btn-link btn-info btn-just-icon like"><i class="material-icons">favorite</i></a>

                    <a href="{{ url_for('home_blueprint.update_sales', sales_id=entry.id) }}" class="btn btn-link btn-warning btn-just-icon edit"><i class="material-icons">dvr</i></a>

                    <button type="button" class="btn btn-link btn-danger btn-just-icon remove" data-toggle="modal" data-target="#deleteModal"><i class="material-icons">close</i></button>
                  </td>
                  {% endif %}

                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Permenently Delete Entry?</h5>

                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{ url_for('home_blueprint.delete_sales', sales_id=entry.id) }}" method="POST">
                              <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>

                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <!-- end content-->
      </div>
      <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
  </div>

{% endblock content %}

{% block javascripts %}  

  <script>
    $(document).ready(function() {
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search records",
        }
      });

      var table = $('#datatable').DataTable();

      // Edit record
      table.on('click', '.edit', function() {
        $tr = $(this).closest('tr');
        var data = table.row($tr).data();
        alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
      });

      // Delete a record
      table.on('click', '.remove', function(e) {
        $tr = $(this).closest('tr');
        table.row($tr).remove().draw();
        e.preventDefault();
      });

      //Like record
      table.on('click', '.like', function() {
        alert('You clicked on Like button');
      });
    });
  </script>

{% endblock javascripts %}

code/master/app/home/templates/add-sales.html
{% extends "layouts/base.html" %}

{% block title %} Forms Regular {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-12">
      <div class="card ">
        <div class="card-header card-header-rose card-header-text">
          <div class="card-text">
            <h4 class="card-title">Add Sale</h4>
          </div>
        </div>
        <div class="card-body ">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div style="border-bottom: solid thin black; font-size: 24px;">Customer Details</div>
            <br>
            <div class="row">
              <br>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="cust_name" class="bmd-label-floating">First Name</label>
                  {{ form.cust_fname(class="form-control",id="cust_fname") }}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="cust_name" class="bmd-label-floating">Last Name</label>
                  {{ form.cust_lname(class="form-control",id="cust_lname") }}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="cust_email" class="bmd-label-floating">Customer Email</label>
                  {{ form.email(type='email', class="form-control", id="cust_email")}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="cust_num" class="bmd-label-floating">Customer Phone Number</label>
                  {{ form.cust_phone_no(class="form-control", id="cust_num")}}
                </div>
              </div>
            </div>
            <br>
            <div style="border-bottom: solid thin black; font-size: 24px;">Product Details</div>
            <br>
            <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="product_code" class="bmd-label-floating">Product Code</label>
                    {{ form.product_code(class="form-control", id="product_code")}}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="qnt" class="bmd-label-floating">Qnt</label>
                    {{ form.qnt(class="form-control", id="qnt")}}
                  </div>
                </div>
                <div class="form-group">
                  <label for="product_price" class="bmd-label-floating">Price</label>
                  {{ form.product_price(class="form-control", id="product_price")}}
                </div>
                <div class="col-md-6">
                  <!--*19240*-->
                  <select class="selectpicker" data-style="select-with-transition" title="Warranty Status" data-size="7">
                    <option disabled>WARRANTY STATUS</option>
                    <option value="1">No Warranty</option>
                    <option value="2">6 months</option>
                    <option value="3">12 months</option>
                  </select>
                </div>
                <div class="col-md-6">
                  <!--*19240*-->
                  <select class="selectpicker" data-style="select-with-transition" title="Delivery" data-size="7">
                    <option disabled> DELIVERY</option>
                    <option value="4">Yes</option>
                    <option value="5">No</option>
                  </select>
                </div>
            </div>
            <div class="">
              {{ form.submit(type="submit", class="btn btn-fill btn-rose") }}
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

code/master/app/home/templates/calendar.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="header text-center">
    <h3 class="title">FullCalendar.io</h3>
    <p class="category">Handcrafted by our friends from
      <a target="_blank" href="https://fullcalendar.io/">FullCalendar.io</a>. Please checkout their
      <a href="https://fullcalendar.io/docs/" target="_blank">full documentation.</a>
    </p>
  </div>
  <div class="row">
    <div class="col-md-10 ml-auto mr-auto">
      <div class="card card-calendar">
        <div class="card-body ">
          <div id="fullCalendar"></div>
        </div>
      </div>
    </div>
  </div>
    
{% endblock content %}

{% block javascripts %}

  <script>
    $(document).ready(function() {
      md.initFullCalendar();
    });
  </script>
  
{% endblock javascripts %}

code/master/app/home/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">weekend</i>
          </div>
          <p class="card-category">Store Visits</p>
          <h3 class="card-title">184</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">date_range</i> Last 24 Hours
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-rose card-header-icon">
          <div class="card-icon">
            <i class="material-icons">equalizer</i>
          </div>
          <p class="card-category">Website Visits</p>
          <h3 class="card-title">75.521</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">local_offer</i> Tracked from Google Analytics
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">store</i>
          </div>
          <p class="card-category">Revenue</p>
          <h3 class="card-title">$34,245</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">date_range</i> Last 24 Hours
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-info card-header-icon">
          <div class="card-icon">
            <i class="fa fa-twitter"></i>
          </div>
          <p class="card-category">Followers</p>
          <h3 class="card-title">+245</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">update</i> Just Updated
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-rose" data-header-animation="true">
          <div class="ct-chart" id="websiteViewsChart"></div>
        </div>
        <div class="card-body">
          <div class="card-actions">
            <button type="button" class="btn btn-danger btn-link fix-broken-card">
              <i class="material-icons">build</i> Fix Header!
            </button>
            <button type="button" class="btn btn-info btn-link" rel="tooltip" data-placement="bottom" title="Refresh">
              <i class="material-icons">refresh</i>
            </button>
            <button type="button" class="btn btn-default btn-link" rel="tooltip" data-placement="bottom" title="Change Date">
              <i class="material-icons">edit</i>
            </button>
          </div>
          <h4 class="card-title">Website Views</h4>
          <p class="card-category">Last Campaign Performance</p>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">access_time</i> campaign sent 2 days ago
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-success" data-header-animation="true">
          <div class="ct-chart" id="dailySalesChart"></div>
        </div>
        <div class="card-body">
          <div class="card-actions">
            <button type="button" class="btn btn-danger btn-link fix-broken-card">
              <i class="material-icons">build</i> Fix Header!
            </button>
            <button type="button" class="btn btn-info btn-link" rel="tooltip" data-placement="bottom" title="Refresh">
              <i class="material-icons">refresh</i>
            </button>
            <button type="button" class="btn btn-default btn-link" rel="tooltip" data-placement="bottom" title="Change Date">
              <i class="material-icons">edit</i>
            </button>
          </div>
          <h4 class="card-title">Daily Sales</h4>
          <p class="card-category">
            <span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.</p>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">access_time</i> updated 4 minutes ago
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-info" data-header-animation="true">
          <div class="ct-chart" id="completedTasksChart"></div>
        </div>
        <div class="card-body">
          <div class="card-actions">
            <button type="button" class="btn btn-danger btn-link fix-broken-card">
              <i class="material-icons">build</i> Fix Header!
            </button>
            <button type="button" class="btn btn-info btn-link" rel="tooltip" data-placement="bottom" title="Refresh">
              <i class="material-icons">refresh</i>
            </button>
            <button type="button" class="btn btn-default btn-link" rel="tooltip" data-placement="bottom" title="Change Date">
              <i class="material-icons">edit</i>
            </button>
          </div>
          <h4 class="card-title">Completed Tasks</h4>
          <p class="card-category">Last Campaign Performance</p>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">access_time</i> campaign sent 2 days ago
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">weekend</i>
          </div>
          <p class="card-category">Bookings</p>
          <h3 class="card-title">184</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons text-danger">warning</i>
            <a href="#pablo">Get More Space...</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-rose card-header-icon">
          <div class="card-icon">
            <i class="material-icons">equalizer</i>
          </div>
          <p class="card-category">Website Visits</p>
          <h3 class="card-title">75.521</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">local_offer</i> Tracked from Google Analytics
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">store</i>
          </div>
          <p class="card-category">Revenue</p>
          <h3 class="card-title">$34,245</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">date_range</i> Last 24 Hours
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-info card-header-icon">
          <div class="card-icon">
            <i class="fa fa-twitter"></i>
          </div>
          <p class="card-category">Followers</p>
          <h3 class="card-title">+245</h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons">update</i> Just Updated
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
  
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="/static/assets/js/plugins/jquery-jvectormap.js"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

      md.initVectorMap();

    });
  </script>

{% endblock javascripts %}

code/master/app/home/templates/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="page-header error-page header-filter" style="background-image: url('/static/assets/img/clint-mckoy.jpg')">
    <!--   you can change the color of the filter page using: data-color="blue | green | orange | red | purple" -->
    <div class="content-center">
      <div class="row">
        <div class="col-md-12">
          <h1 class="title">403</h1>
          <h2>Access denied</h2>
          <h4>
            Please contact support or <a href="{{ url_for('base_blueprint.login') }}">authenticate</a>.
          </h4>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      md.checkFullPageBackgroundImage();
    });
  </script>

{% endblock javascripts %}

code/master/app/home/templates/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="page-header error-page header-filter" style="background-image: url('/static/assets/img/clint-mckoy.jpg')">
    <!--   you can change the color of the filter page using: data-color="blue | green | orange | red | purple" -->
    <div class="content-center">
      <div class="row">
        <div class="col-md-12">
          <h1 class="title">404</h1>
          <h2>Page not found :(</h2>
          <h4>Ooooups! Looks like you got lost.</h4>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      md.checkFullPageBackgroundImage();
    });
  </script>

{% endblock javascripts %}

code/master/app/home/templates/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="page-header error-page header-filter" style="background-image: url('/static/assets/img/clint-mckoy.jpg')">
    <!--   you can change the color of the filter page using: data-color="blue | green | orange | red | purple" -->
    <div class="content-center">
      <div class="row">
        <div class="col-md-12">
          <h1 class="title">500</h1>
          <h2>Server error</h2>
          <h4>Please contact support.</h4>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      md.checkFullPageBackgroundImage();
    });
  </script>

{% endblock javascripts %}

code/master/app/home/templates/page-lock.html
{% extends "layouts/base-auth.html" %}

{% block title %} Lock {% endblock title %}

{% block content %}

    <div class="page-header lock-page header-filter" style="background-image: url('/static/assets/img/lock.jpg')">
      <!--   you can change the color of the filter page using: data-color="blue | green | orange | red | purple" -->
      <div class="container">
        <div class="row">
          <div class="col-md-4 ml-auto mr-auto">
            <div class="card card-profile text-center card-hidden">
              <div class="card-header ">
                <div class="card-avatar">
                  <a href="#pablo">
                    <img class="img" src="/static/assets/img/faces/avatar.jpg">
                  </a>
                </div>
              </div>
              <div class="card-body ">
                <h4 class="card-title">Tania Andrew</h4>
                <div class="form-group">
                  <label for="exampleInput1" class="bmd-label-floating">Enter Password</label>
                  <input type="password" class="form-control" id="exampleInput1">
                </div>
              </div>
              <div class="card-footer justify-content-center">
                <a href="/" class="btn btn-rose btn-round">Unlock</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% include 'includes/footer-auth.html' %}

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}    

  <script>
    $(document).ready(function() {
      md.checkFullPageBackgroundImage();
      setTimeout(function() {
        // after 1000 ms we add the class animated to the login/register card
        $('.card').removeClass('card-hidden');
      }, 700);
    });
  </script>

{% endblock javascripts %}